server:
  port: 4000
spring:
  application:
    name: geekedu-oss
minio:
  url: http://192.168.150.101:9000
  accessKey: admin
  secretKey: admin123
aliyun:
  oss:
    accessKeyID: 
    accessKeySecret: 
    endPoint: 
    bucketName: 
